### ISSUE TITLE
Question: Dual-setup for both Kodi/standalone & OS/Browser?

### ISSUE THREAD

**Issue by ghost** [graysky2/streamzap#3]
@graysky2 

1st, THANKS for this!!  I've been slogging thru various streamzap+kodi headaches for years.  This makes it trivial -- works perfectly!

I've got a question about modifying/adapting these configs to adapt to BOTH, e.g., Kodi and Netflix-in-a-Browser.

I run kodi on linux.

This

90-streamzap-disable.conf

does what is should and disables the keyboard-in-linux response.  Which is perfect in a just-kodi setup

My media env, though, is Kodi/standalone + Netflix (In Firefox or Chrome)

What I'd like to do is setup the streamzap/lirc config so that
(1) when running Kodi it functions as a Kodi remote, and ignores system/keyboard functionality
*and*
(2) when streaming Netflix in a browser, it functions to control System/keyboard (e.g., for system volume) anf Browser (e.g., toggle full screen, in-browser Netflix controls).

Can these scripts be setup "conditionally" for use by Kodi AND OS/Browser for Netflix?
Is this even the right tool for the job?

**Comment by graysky2** [comment]
Why not use the [netflix plugin](https://forum.kodi.tv/showthread.php?tid=329767) for kodi?  I believe it requires v18 but that is nearly final.  What distro are you running?  Likely, you can obtain a v18rc3 package.

**Comment by ghost** [comment]
I'm looking for standalone in-browser support.

I can get that done with Lirc/Streamzap I suppose if I *EN*able the system-keyboard emulation.

It'll conflict with the in-Kodi use then.

So, my question about setting it up conditionally in one, consolidated Lirc config.

Somehow.

**Comment by graysky2** [comment]
You can have [application specific actions](https://wiki.archlinux.org/index.php/LIRC#Application-specific_actions) with lirc, but your issue is that you want the built-in support _disabled_ (via `/etc/X11/xorg.conf.d/90-streamzap-disable.conf`) for one application and enabled for another if I understand correctly.  I don't think that's possible without some shell script fuckery manipulating things... you might want to post to the lirc ML but it's definitely beyond the scope of my configs ;)
